name: Deploy to GitHub Release

description: This GitHub Action deploys built artifacts to GitHub Release.

runs:
  using: composite
  steps:
    - name: Download artifatcs
      uses: actions/download-artifact@v4
      with:
        name: manifest
        path: manifest
    - name: Archive artifatcs
      shell: pwsh
      run: Compress-Archive -Path manifest/* -DestinationPath Commistant_${{env.BUILD_VERSION}}.zip
    - name: Create release
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
      with:
        files: Commistant_${{env.BUILD_VERSION}}.zip
