//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karamem0.Commistant.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karamem0.Commistant.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;object&quot;,&quot;properties&quot;:{&quot;type&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;This must be \&quot;会議終了前\&quot;.&quot;},&quot;value&quot;:{&quot;type&quot;:&quot;object&quot;,&quot;description&quot;:&quot;The settings about message to send before the end of the meeting.&quot;,&quot;properties&quot;:{&quot;schedule&quot;:{&quot;type&quot;:&quot;integer&quot;,&quot;description&quot;:&quot;The frequency in minutes.&quot;},&quot;message&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;The message.&quot;},&quot;url&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;The attached URL.&quot;}}}},&quot;required&quot;:[&quot;type&quot;,&quot;value&quot;]}.
        /// </summary>
        public static string EndMeetingJson
        {
            get
            {
                return ResourceManager.GetString("EndMeetingJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;object&quot;,&quot;properties&quot;:{&quot;type&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;This must be \&quot;会議中\&quot;.&quot;},&quot;value&quot;:{&quot;type&quot;:&quot;object&quot;,&quot;description&quot;:&quot;The settings about message to send during the meeting.&quot;,&quot;properties&quot;:{&quot;schedule&quot;:{&quot;type&quot;:&quot;integer&quot;,&quot;description&quot;:&quot;The frequency in minutes.&quot;},&quot;message&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;The message.&quot;},&quot;url&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;The attached URL.&quot;}}}},&quot;required&quot;:[&quot;type&quot;,&quot;value&quot;]}.
        /// </summary>
        public static string InMeetingJson
        {
            get
            {
                return ResourceManager.GetString("InMeetingJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;object&quot;,&quot;properties&quot;:{&quot;type&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;This must be \&quot;初期化\&quot;.&quot;}},&quot;required&quot;:[&quot;type&quot;]}.
        /// </summary>
        public static string ResetJson
        {
            get
            {
                return ResourceManager.GetString("ResetJson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;object&quot;,&quot;properties&quot;:{&quot;type&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;This must be \&quot;会議開始後\&quot;.&quot;},&quot;value&quot;:{&quot;type&quot;:&quot;object&quot;,&quot;description&quot;:&quot;The settings about message to send after the start of the meeting.&quot;,&quot;properties&quot;:{&quot;schedule&quot;:{&quot;type&quot;:&quot;integer&quot;,&quot;description&quot;:&quot;The frequency in minutes.&quot;},&quot;message&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;The message.&quot;},&quot;url&quot;:{&quot;type&quot;:&quot;string&quot;,&quot;description&quot;:&quot;The attached URL.&quot;}}}},&quot;required&quot;:[&quot;type&quot;,&quot;value&quot;]}.
        /// </summary>
        public static string StartMeetingJson
        {
            get
            {
                return ResourceManager.GetString("StartMeetingJson", resourceCulture);
            }
        }
    }
}
