name: Test source

description: This GitHub Action tests sources and uploads reports

runs:
  using: composite
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x
    - name: Test source
      shell: pwsh
      run: |
        dotnet test `
          Karamem0.Commistant.Test/Karamem0.Commistant.Test.csproj `
          -p:AltCover=true `
          -- NUnit.TestOutputXml=${{github.workspace}}/source/server/test
      working-directory: source/server
    - name: Test results
      uses: enricomi/publish-unit-test-result-action/linux@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6
      if: always()
      with:
        files: source/server/test/*.xml
        check_name: Bot test results
    - name: Upload coverage reports
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      if: always()
      with:
        fail_ci_if_error: true
        token: ${{env.CODECOV_TOKEN}}
        slug: karamem0/commistant
