on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  run:
    name: Run
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Update index.html
        shell: pwsh
        run: |
          $content = Get-Content -Path ${{env.FILE_PATH}}
          $content = $content -replace "{{APP_DOMAIN_NAME}}", "${{vars.APP_DOMAIN_NAME}}"
          Out-File -FilePath ${{env.FILE_PATH}} -InputObject $content -Encoding UTF8
        env:
          FILE_PATH: source/server/Karamem0.Commistant.Bot/wwwroot/index.html
      - name: Restore source
        run: dotnet restore
        working-directory: source/server
      - name: Test source
        shell: pwsh
        run: |
          dotnet test `
            Karamem0.Commistant.Tests/Karamem0.Commistant.Tests.csproj `
            --filter TestCategory=Karamem0.Commistant.Bot `
            -p:AltCover=true `
            -- NUnit.TestOutputXml=${{github.workspace}}/source/server/test
        working-directory: source/server
      - name: Build source
        shell: pwsh
        run: |
          dotnet publish `
            Karamem0.Commistant.Bot/Karamem0.Commistant.Bot.csproj `
            -c Release `
            -p:PublishDir=${{github.workspace}}/source/server/build `
            -p:Version=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}.${{github.run_number}}
        working-directory: source/server
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bot
          path: source/server/build
          include-hidden-files: true
      - name: Upload test results
        uses: enricomi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: source/server/test/*.xml
          check_name: Bot test results
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
          slug: karamem0/commistant
