name: Build source

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions: {}

jobs:
  run:
    name: Run
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Update microsoft-identity-association.json
        shell: pwsh
        run: |
          $content = Get-Content -Path ${{env.FILE_PATH}}
          $content = $content -Replace "{{APP_CLIENT_ID}}", "${{vars.APP_CLIENT_ID}}"
          Out-File -FilePath ${{env.FILE_PATH}} -InputObject $content -Encoding UTF8
        env:
          FILE_PATH: source/client/public/.well-known/microsoft-identity-association.json
      - name: Update .env
        shell: pwsh
        run: |
          $content = Get-Content -Path ${{env.FILE_PATH}}
          $content = $content -Replace "{{WEB_HOST_NAME}}", "${{vars.WEB_HOST_NAME}}"
          $content = $content -Replace "{{FUNCTION_HOST_NAME}}", "${{vars.FUNCTION_HOST_NAME}}"
          $content = $content -Replace "{{TELEMETRY_CONNECTION_STRING}}", "${{vars.TELEMETRY_CONNECTION_STRING}}"
          Out-File -FilePath ${{env.FILE_PATH}} -InputObject $content -Encoding UTF8
        env:
          FILE_PATH: source/client/.env
      - name: Update package.json
        run: npm version ${{vars.BUILD_VERSION}} --no-git-tag-version
        working-directory: source/client
      - name: Restore client
        run: npm ci
        working-directory: source/client
      - name: Audit client
        run: npm audit --omit=dev
        working-directory: source/client
      - name: Restore server
        run: dotnet restore
        working-directory: source/server
      - name: Build web
        shell: pwsh
        run: |
          dotnet publish `
            Karamem0.Commistant.Web/Karamem0.Commistant.Web.csproj `
            -c Release `
            -p:PublishDir=${{github.workspace}}/source/server/build/web `
            -p:Version=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}.${{github.run_number}}
        working-directory: source/server
      - name: Build function
        shell: pwsh
        run: |
          dotnet publish `
            Karamem0.Commistant.Function/Karamem0.Commistant.Function.csproj `
            -c Release `
            -p:PublishDir=${{github.workspace}}/source/server/build/function `
            -p:Version=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}.${{github.run_number}}
        working-directory: source/server
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: source/server/build
          include-hidden-files: true
