on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  run:
    name: Run
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore source
        run: dotnet restore
        working-directory: source/server
      - name: Build source
        shell: pwsh
        run: |
          dotnet publish `
            Karamem0.Commistant.Functions/Karamem0.Commistant.Functions.csproj `
            -c Release `
            -p:PublishDir=${{github.workspace}}/source/server/build `
            -p:Version=${{vars.BUILD_VERSION}}.${{github.run_number}} `
            -p:FileVersion=${{vars.BUILD_VERSION}}.${{github.run_number}}
        working-directory: source/server
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: func
          path: source/server/build
          include-hidden-files: true
