name: Deploy bot to Azure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions: {}

jobs:
  run:
    name: Run
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bot
          path: bot
      - name: Connect to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy artifacts
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{vars.AZURE_APP_SERVICE_NAME_BOT}}
          package: bot
