name: Deploy to Azure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions: {}

jobs:
  run:
    name: Run
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Connect to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Deploy web
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{vars.WEB_APP_NAME}}
          package: build/web
      - name: Deploy function
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{vars.FUNCTION_APP_NAME}}
          package: build/function
