on:
  push:
    branches:
      - develop

env:
  BUILD_VERSION: 3.0.3.${{github.run_number}}
  BUILD_CONFIGURATION: Release

jobs:
  build-web:
    environment: development
    runs-on: windows-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x
      - name: Rewrite .env
        shell: pwsh
        run: |
          $content = Get-Content -Path .env
          $content = $content -replace "{{PUBLIC_URL}}", "${{secrets.PUBLIC_URL}}"
          $content = $content -replace "{{TELEMETRY_CONNECTION_STRING}}", "${{secrets.TELEMETRY_CONNECTION_STRING}}"
          Out-File -FilePath .env -InputObject $content -Encoding UTF8
        working-directory: source/client
      - name: Restore client
        run: npm ci
        working-directory: source/client
      - name: Audit client
        run: npm audit --omit=dev
        working-directory: source/client
      - name: Restore server
        run: dotnet restore
        working-directory: source/server/Karamem0.Commistant.Web
      - name: Test source
        run: dotnet test --filter TestCategory=Karamem0.Commistant.Web
        working-directory: source/server
      - name: Build source
        run: |
          dotnet publish `
            -c ${{env.BUILD_CONFIGURATION}} `
            -p:PublishDir=build `
            -p:Version=${{env.BUILD_VERSION}} `
            -p:FileVersion=${{env.BUILD_VERSION}}
        working-directory: source/server/Karamem0.Commistant.Web
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: commistant-web
          path: source/server/Karamem0.Commistant.Web/build
  build-func:
    environment: development
    runs-on: windows-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x
      - name: Restore source
        run: dotnet restore
        working-directory: source/server/Karamem0.Commistant.Functions
      - name: Test source
        run: dotnet test --filter TestCategory=Karamem0.Commistant.Functions
        working-directory: source/server
      - name: Build source
        run: |
          dotnet publish `
            -c ${{env.BUILD_CONFIGURATION}} `
            -p:PublishDir=build `
            -p:Version=${{env.BUILD_VERSION}} `
            -p:FileVersion=${{env.BUILD_VERSION}}
        working-directory: source/server/Karamem0.Commistant.Functions
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: commistant-func
          path: source/server/Karamem0.Commistant.Functions/build
  build-bot:
    environment: development
    runs-on: windows-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x
      - name: Rewrite index.html
        shell: pwsh
        run: |
          $content = Get-Content -Path wwwroot/index.html
          $content = $content -replace "{{AppDomain}}", "${{secrets.APP_DOMAIN}}"
          Out-File -FilePath wwwroot/index.html -InputObject $content -Encoding UTF8
        working-directory: source/server/Karamem0.Commistant.Bot
      - name: Restore source
        run: dotnet restore
        working-directory: source/server/Karamem0.Commistant.Bot
      - name: Test source
        run: dotnet test --filter TestCategory=Karamem0.Commistant.Bot
        working-directory: source/server
      - name: Build source
        run: |
          dotnet publish `
            -c ${{env.BUILD_CONFIGURATION}} `
            -p:PublishDir=build `
            -p:Version=${{env.BUILD_VERSION}} `
            -p:FileVersion=${{env.BUILD_VERSION}}
        working-directory: source/server/Karamem0.Commistant.Bot
      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: commistant-bot
          path: source/server/Karamem0.Commistant.Bot/build
  build-manifest:
    environment: development
    runs-on: windows-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v3
      - name: Rewrite manifest.json
        shell: pwsh
        run: |
          $content = Get-Content -Path manifest.json
          $content = $content -Replace '{{AppId}}', '${{secrets.APP_ID}}'
          $content = $content -Replace '{{AppDomain}}', '${{secrets.APP_DOMAIN}}'
          Out-File -FilePath manifest.json -InputObject $content -Encoding UTF8
        working-directory: manifest
      - name: Upload manifest files
        uses: actions/upload-artifact@v3
        with:
          name: commistant-manifest
          path: manifest
  deploy:
    needs:
      - build-web
      - build-func
      - build-bot
    if: contains(github.ref, 'refs/heads/develop')
    environment: development
    runs-on: windows-latest
    steps:
      - name: Connect to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Download web build files
        uses: actions/download-artifact@v3
        with:
          name: commistant-web
          path: artifact/commistant-web
      - name: Deploy web
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.AZURE_WEB_NAME}}
          package: artifact/commistant-web
      - name: Download bot build files
        uses: actions/download-artifact@v3
        with:
          name: commistant-bot
          path: artifact/commistant-bot
      - name: Deploy bot
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.AZURE_BOT_NAME}}
          package: artifact/commistant-bot
      - name: Download func build files
        uses: actions/download-artifact@v3
        with:
          name: commistant-func
          path: artifact/commistant-func
      - name: Deploy func
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{secrets.AZURE_FUNC_NAME}}
          package: artifact/commistant-func
  release:
    needs:
      - build-manifest
    if: contains(github.ref, 'refs/tags/')
    environment: development
    runs-on: windows-latest
    steps:
      - name: Download manifest files
        uses: actions/download-artifact@v3
        with:
          name: commistant-manifest
          path: artifact
      - name: Archive manifest files
        run: Compress-Archive -Path artifact/* -DestinationPath manifest_${{env.BUILD_VERSION}}.zip
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: |
            manifest_${{env.BUILD_VERSION}}.zip
