on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*.*.*

env:
  BUILD_VERSION: 1.1.1.${{github.run_number}}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set environment variables
        if: contains(github.ref, 'refs/heads/main')
        run: |
          ConvertFrom-Json -InputObject '${{secrets.PRD_GITHUB_ENV}}' `
            | %{ $_.PSObject.Properties } `
            | %{ Add-Content -Path $env:GITHUB_ENV -Value ($_.Name + '=' + $_.Value) }
      - name: Set environment variables
        if: contains(github.ref, 'refs/heads/develop')
        run: |
          ConvertFrom-Json -InputObject '${{secrets.DEV_GITHUB_ENV}}' `
            | %{ $_.PSObject.Properties } `
            | %{ Add-Content -Path $env:GITHUB_ENV -Value ($_.Name + '=' + $_.Value) }
      - name: Checkout repos
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Restore source
        run: |
          dotnet restore source/server/Karamem0.Commistant.sln
      - name: Build web
        run: |
          dotnet publish source/server/Karamem0.Commistant.Web/Karamem0.Commistant.Web.csproj `
            -c Release `
            -o artifact/commistant-web `
            -p:Version=${{env.BUILD_VERSION}} `
            -p:FileVersion=${{env.BUILD_VERSION}}
      - name: Upload web build files
        uses: actions/upload-artifact@v2
        with:
          name: commistant-web
          path: artifact/commistant-web
      - name: Build functions
        run: |
          dotnet publish source/server/Karamem0.Commistant.Functions/Karamem0.Commistant.Functions.csproj `
            -c Release `
            -o artifact/commistant-func `
            -p:Version=${{env.BUILD_VERSION}} `
            -p:FileVersion=${{env.BUILD_VERSION}}
      - name: Upload functions build files
        uses: actions/upload-artifact@v2
        with:
          name: commistant-func
          path: artifact/commistant-func
      - name: Rewrite manifest.json
        run: |
          $content = Get-Content -Path manifest/manifest.json
          $content = $content -Replace '{{AppId}}', '${{env.APP_ID}}'
          $content = $content -Replace '{{AppDomain}}', '${{env.APP_DOMAIN}}'
          Out-File -FilePath manifest/manifest.json -InputObject $content -Encoding UTF8
      - name: Upload manifest files
        uses: actions/upload-artifact@v2
        with:
          name: commistant-manifest
          path: manifest
  deploy:
    needs: build
    if: contains(github.ref, 'refs/heads/')
    runs-on: windows-latest
    steps:
      - name: Set environment variables
        if: contains(github.ref, 'refs/heads/main')
        run: |
          ConvertFrom-Json -InputObject '${{secrets.PRD_GITHUB_ENV}}' `
            | %{ $_.PSObject.Properties } `
            | %{ Add-Content -Path $env:GITHUB_ENV -Value ($_.Name + '=' + $_.Value) }
      - name: Set environment variables
        if: contains(github.ref, 'refs/heads/develop')
        run: |
          ConvertFrom-Json -InputObject '${{secrets.DEV_GITHUB_ENV}}' `
            | %{ $_.PSObject.Properties } `
            | %{ Add-Content -Path $env:GITHUB_ENV -Value ($_.Name + '=' + $_.Value) }
      - name: Connect to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Download web build files
        uses: actions/download-artifact@v2
        with:
          name: commistant-web
          path: artifact/commistant-web
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.APP_WEB_NAME}}
          package: artifact/commistant-web
      - name: Download functions build files
        uses: actions/download-artifact@v2
        with:
          name: commistant-func
          path: artifact/commistant-func
      - name: Deploy to Azure Functions
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.APP_FUNC_NAME}}
          package: artifact/commistant-func
  release:
    needs: build
    if: contains(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - name: Download manifest files
        uses: actions/download-artifact@v2
        with:
          name: commistant-manifest
          path: artifact
      - name: Archive manifest files
        run: Compress-Archive -Path artifact/* -DestinationPath manifest_${{env.BUILD_VERSION}}.zip
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: |
            manifest_${{env.BUILD_VERSION}}.zip
