on:
  push:
    branches:
      - main

jobs:
  build-bot:
    name: Build bot
    uses: ./.github/workflows/build-bot.yml
    secrets: inherit
    with:
      environment: prd
  deploy-bot:
    name: Deploy bot
    needs: build-bot
    uses: ./.github/workflows/deploy-bot.yml
    secrets: inherit
    with:
      environment: prd
  build-web:
    name: Build web
    uses: ./.github/workflows/build-web.yml
    secrets: inherit
    with:
      environment: prd
  deploy-web:
    name: Deploy web
    needs: build-web
    uses: ./.github/workflows/deploy-web.yml
    secrets: inherit
    with:
      environment: prd
  build-func:
    name: Build func
    uses: ./.github/workflows/build-func.yml
    secrets: inherit
    with:
      environment: prd
  deploy-func:
    name: Deploy func
    needs: build-func
    uses: ./.github/workflows/deploy-func.yml
    secrets: inherit
    with:
      environment: prd
  build-manifest:
    name: Build manifest
    uses: ./.github/workflows/build-manifest.yml
    secrets: inherit
    with:
      environment: prd
