name: Test source

on:
  workflow_call: {}

permissions:
  checks: write

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Test source
        shell: pwsh
        run: |
          dotnet test `
            Karamem0.Commistant.Tests/Karamem0.Commistant.Tests.csproj `
            -p:AltCover=true `
            -- NUnit.TestOutputXml=${{github.workspace}}/source/server/test
        working-directory: source/server
      - name: Test results
        uses: enricomi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: source/server/test/*.xml
          check_name: Bot test results
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
          slug: karamem0/commistant
