on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*.*.*

jobs:
  deploy-development:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/workflow.deploy.yml
    secrets:
      APP_CLIENT_ID: ${{secrets.APP_CLIENT_ID}}
      APP_DOMAIN_NAME: ${{secrets.APP_DOMAIN_NAME}}
      AZURE_BOT_NAME: ${{secrets.AZURE_BOT_NAME}}
      AZURE_FUNC_NAME: ${{secrets.AZURE_FUNC_NAME}}
      AZURE_WEB_NAME: ${{secrets.AZURE_WEB_NAME}}
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      TELEMETRY_CONNECTION_STRING: ${{secrets.TELEMETRY_CONNECTION_STRING}}
    with:
      environment: development
  deploy-production:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/workflow.deploy.yml
    secrets:
      APP_CLIENT_ID: ${{secrets.APP_CLIENT_ID}}
      APP_DOMAIN_NAME: ${{secrets.APP_DOMAIN_NAME}}
      AZURE_BOT_NAME: ${{secrets.AZURE_BOT_NAME}}
      AZURE_FUNC_NAME: ${{secrets.AZURE_FUNC_NAME}}
      AZURE_WEB_NAME: ${{secrets.AZURE_WEB_NAME}}
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      TELEMETRY_CONNECTION_STRING: ${{secrets.TELEMETRY_CONNECTION_STRING}}
    with:
      environment: production
  create-release:
    if: contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/workflow.release.yml
    secrets:
      APP_CLIENT_ID: ${{secrets.APP_CLIENT_ID}}
      APP_DOMAIN_NAME: ${{secrets.APP_DOMAIN_NAME}}
    with:
      environment: production
